columns:
  - satisfaction_level: float
  - last_evaluation: float
  - number_project: int
  - average_montly_hours: float
  - time_spend_company: float
  - work_accident: int
  - left: category
  - promotion_last_5years: int
  - is_smoker: category
  - department: category
  - salary: category


numerical_columns:
  - satisfaction_level
  - last_evaluation
  - number_project
  - average_montly_hours
  - time_spend_company
  - work_accident
  - promotion_last_5years


categorical_columns:
  - left
  - is_smoker
  - department
  - salary


drop_columns: _id

# for data transformation
num_features:
  - average_monthly_hours


# mm_columns:
#   - Annual_Premium